[general]
name = "time"
version = "1.0.1"
description = "Provides functions related to time and date."

[build]
files = ["time.fix"]
objects = ["lib.o"]
preliminary_commands = [["make", "lib.o"]]

[build.test]
files = ["test.fix"]
